# Generated by Django 4.1.3 on 2022-12-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpro',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Unable To Complete Delivery', 'Unable To Complete Delivery')], default='Pending', max_length=200),
        ),
    ]
